name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      GO111MODULE: off
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - name: test
        run: make test
      - name: dist
        run: make dist
      - name: prepare-test
        run: make prepare-test
      - name: test e2e
        run: make test-e2e


